version: '2.3'
services:
  postgres:
    container_name: robinhood_postgres
    image: postgres:11.1-alpine
    networks:
      jenkins_network:
        ipv4_address: 172.20.0.2
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    volumes:
      - /Users/s89609/postgresql:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:lts
    container_name: robinhood_sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      jenkins_network:
        ipv4_address: 172.20.0.4
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonarpasswd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    depends_on: 
      - postgres
  
  jenkins:
    image: jenkins/jenkins:lts
    networks:
      jenkins_network:
        ipv4_address: 172.20.0.3
        
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: robinhood_jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    environment:
      JVM_OPTS: -Xmx4048m
      GRADLE_OPTS: -Xmx4048m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false

networks:
  jenkins_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
